# coding=utf-8
# Copyright 2018 The Google AI Language Team Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# pylint: disable=invalid-name, missing-function-docstring
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from tensorflow.core.example import example_pb2 as tensorflow_dot_core_dot_example_dot_example__pb2


class PreprocessingStub(object):
  """Missing associated documentation comment in .proto file."""

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.PopExample = channel.unary_unary(
        '/language.realm.Preprocessing/PopExample',
        request_serializer=tensorflow_dot_core_dot_example_dot_example__pb2
        .Example.SerializeToString,
        response_deserializer=tensorflow_dot_core_dot_example_dot_example__pb2
        .Example.FromString,
    )


class PreprocessingServicer(object):
  """Missing associated documentation comment in .proto file."""

  def PopExample(self, request, context):
    """Return a tf.Example given an unused (usually empty) input tf.Example."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PreprocessingServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'PopExample':
          grpc.unary_unary_rpc_method_handler(
              servicer.PopExample,
              request_deserializer=tensorflow_dot_core_dot_example_dot_example__pb2
              .Example.FromString,
              response_serializer=tensorflow_dot_core_dot_example_dot_example__pb2
              .Example.SerializeToString,
          ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'language.realm.Preprocessing', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Preprocessing(object):
  """Missing associated documentation comment in .proto file."""

  @staticmethod
  def PopExample(request,
                 target,
                 options=(),
                 channel_credentials=None,
                 call_credentials=None,
                 compression=None,
                 wait_for_ready=None,
                 timeout=None,
                 metadata=None):
    return grpc.experimental.unary_unary(
        request, target, '/language.realm.Preprocessing/PopExample',
        tensorflow_dot_core_dot_example_dot_example__pb2.Example
        .SerializeToString,
        tensorflow_dot_core_dot_example_dot_example__pb2.Example.FromString,
        options, channel_credentials, call_credentials, compression,
        wait_for_ready, timeout, metadata)
