# coding=utf-8
# Copyright 2018 The Google AI Language Team Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# -*- coding: utf-8 -*-
# pylint: disable=protected-access
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: preprocessing.proto
"""Automatically generated Python interface for preprocessing.proto."""

from tensorflow.core.example import example_pb2 as tensorflow_dot_core_dot_example_dot_example__pb2

from google.protobuf import descriptor as _descriptor
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='preprocessing.proto',
    package='language.realm',
    syntax='proto2',
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x13preprocessing.proto\x12\x0elanguage.realm\x1a%tensorflow/core/example/example.proto2I\n\rPreprocessing\x12\x38\n\nPopExample\x12\x13.tensorflow.Example\x1a\x13.tensorflow.Example\"\x00',
    dependencies=[
        tensorflow_dot_core_dot_example_dot_example__pb2.DESCRIPTOR,
    ])

_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_PREPROCESSING = _descriptor.ServiceDescriptor(
    name='Preprocessing',
    full_name='language.realm.Preprocessing',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=78,
    serialized_end=151,
    methods=[
        _descriptor.MethodDescriptor(
            name='PopExample',
            full_name='language.realm.Preprocessing.PopExample',
            index=0,
            containing_service=None,
            input_type=tensorflow_dot_core_dot_example_dot_example__pb2
            ._EXAMPLE,
            output_type=tensorflow_dot_core_dot_example_dot_example__pb2
            ._EXAMPLE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_PREPROCESSING)

DESCRIPTOR.services_by_name['Preprocessing'] = _PREPROCESSING

# @@protoc_insertion_point(module_scope)
