# coding=utf-8
# Copyright 2018 The Google AI Language Team Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Pre-tokenize dataset for NQG which uses space-separated tokenization.

Input should be a TSV file, e.g. generated by applying `split_dataset.py` to
the output ofr `spider/write_dataset.py`.
"""

from absl import app
from absl import flags

from language.compgen.nqg.tasks import tsv_utils

from language.compgen.nqg.tasks.spider import nqg_tokenization

FLAGS = flags.FLAGS

flags.DEFINE_string("input", "", "Input tsv file.")

flags.DEFINE_string("output", "", "Output tsv file.")


def main(unused_argv):
  examples = tsv_utils.read_tsv(FLAGS.input)
  new_examples = []
  for source, target in examples:
    new_examples.append((nqg_tokenization.process_source(source),
                         nqg_tokenization.process_target(target)))
  tsv_utils.write_tsv(new_examples, FLAGS.output)


if __name__ == "__main__":
  app.run(main)
